[versions]
agp = "8.10.1"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activityCompose = "1.10.1"
androidx-core-ktx = "1.16.0"
androidx-espresso-core = "3.6.1"
androidx-test-junit = "1.2.1"
appyx = "2.0.1"
arrow = "1.2.4"
compose-multiplatform = "1.7.3"
haze = "0.7.1"
junit = "4.13.2"
kotlin = "2.1.20"
kotlinx-serialization = "1.7.1"
lucide = "1.0.0"
material3 = "1.6.10"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# https://github.com/bumble-tech/appyx
appyx-interactions = { module = "com.bumble.appyx:appyx-interactions", version.ref = "appyx" }
appyx-navigation = { module = "com.bumble.appyx:appyx-navigation", version.ref = "appyx" }
appyx-backstack = { module = "com.bumble.appyx:backstack", version.ref = "appyx" }
appyx-spotlight = { module = "com.bumble.appyx:spotlight", version.ref = "appyx" }
appyx-material3 = { module = "com.bumble.appyx:utils-material3", version.ref = "appyx" }
appyx-multiplatform = { module = "com.bumble.appyx:utils-multiplatform", version.ref = "appyx" }

# https://arrow-kt.io/
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }

# https://github.com/chrisbanes/haze
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }

# https://github.com/composablehorizons/composeicons/tree/main/icons-lucide
composables-icons-lucide = { module = "com.composables:icons-lucide", version.ref = "lucide" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }