default_platform(:ios)

platform :ios do
  lane :build do
    build_app(
      project: "./iosApp/iosApp.xcodeproj",
      configuration: "Debug",
      scheme: "iosApp",
      destination: "generic/platform=iOS",
      skip_codesigning: true,
      skip_archive: true
    )
  end

  lane :test do
    gradle(
      tasks: [
        ':shared:iosSimulatorArm64Test',
        ':shared:iosX64Test',
      ]
    )

    run_tests(
      project: "./iosApp/iosApp.xcodeproj",
      configuration: "Debug",
      scheme: "iosAppUITests",
      device: "iPhone 16 Pro (18.4)",
      ensure_devices_found: true,
      prelaunch_simulator: true,
      fail_build: false,
      reset_simulator: true
    )
  end

  lane :release do
    match(
      type: "appstore",
      readonly: true
    )

    build_ios_app(
      project: "./iosApp/iosApp.xcodeproj",
      scheme: "iosApp",
      configuration: "Release",
      output_directory: "./build",
      output_name: "deploy",
      destination: "generic/platform=iOS",
    )
  end
end

platform :android do
  lane :build do
    gradle(
      task: "assemble",
      build_type: "Debug"
    )
  end

  lane :test do
    gradle(
      task: "testDebugUnitTest"
    )
  end
end
