default_platform(:ios)

platform :ios do
  lane :build do
    build_app(
      project: "./iosApp/iosApp.xcodeproj",
      configuration: "Debug",
      scheme: "iosApp",
      destination: "generic/platform=iOS",
      skip_codesigning: true,
      skip_archive: true
    )
  end

  lane :test do
    gradle(
      tasks: [
        ':shared:iosSimulatorArm64Test',
        ':shared:iosX64Test',
      ]
    )

    run_tests(
      project: "./iosApp/iosApp.xcodeproj",
      configuration: "Debug",
      scheme: "iosAppUITests",
      device: "iPhone 16 Pro (18.4)",
      ensure_devices_found: true,
      prelaunch_simulator: true,
      fail_build: false,
      reset_simulator: true
    )
  end

  lane :release do
    create_keychain(
      name: "keychain",
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      type: "appstore",
      readonly: true,
      keychain_name: "keychain",
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    )

    increment_version_number(
      version_number: ENV["APP_VERSION"],
      xcodeproj: "./iosApp/iosApp.xcodeproj"
    )
    increment_build_number(xcodeproj: "./iosApp/iosApp.xcodeproj")

    build_ios_app(
      project: "./iosApp/iosApp.xcodeproj",
      scheme: "iosApp",
      configuration: "Release",
      output_directory: "./build",
      output_name: "deploy",
      destination: "generic/platform=iOS",
      export_method: "app-store",
    )
  end

  lane :test_deploy do
    version = ENV["APP_VERSION"]
    changelog = ENV["APP_CHANGELOG"] || "No changelog provided."

    pilot(
      api_key_path: "fastlane/key.json",
      ipa: "./build/deploy.ipa",
      app_platform: "ios",
      changelog: changelog,
      beta_app_feedback_email: "lancelot.liu23@imperial.ac.uk",
      beta_app_description: "Test build v#{version} for QA",
      distribute_external: true,
      groups: ["Real People"],
      skip_submission: false,
      skip_waiting_for_build_processing: false
    )
  end
end

platform :android do
  lane :build do
    gradle(
      task: "assemble",
      build_type: "Debug"
    )
  end

  lane :test do
    gradle(
      task: "testDebugUnitTest"
    )
  end
end
